### ISSUE TITLE
加载失败

### ISSUE THREAD

**Issue by yuanjie000** [jessefjxm/Fundamental-Physics-mod-for-Factorio#1]
![bug](https://user-images.githubusercontent.com/20902900/38847554-d294df8a-4234-11e8-987d-6dcd788524e2.png)

factorio：0.16.36

**Comment by jessefjxm** [comment]
应该是自动更新的版本问题。尝试安装下载官网的0.3.0版本看看

**Comment by yuanjie000** [comment]
用了0.3.0后没有问题了，不过用游戏自带的mod下载器下载下来是0.2的版本

**Comment by jessefjxm** [comment]
这个机制有点问题，得开发组背锅了

**Comment by yuanjie000** [comment]
抱歉，打扰了，经过确认，与 _Darkstar_utilities_Low_Spec_0.16.8_ 一块用的时候会出现如下问题
![qq 20180418111757](https://user-images.githubusercontent.com/20902900/38910063-323ed70e-42fa-11e8-8861-e280fed3a938.png)
